[general]
import = ["/home/davs/dotfiles/alacritty/colors.toml"]

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "alacritty"

[font]
size = 13

[font.bold]
family = "DejaVu Sans Mono"

[font.bold_italic]
family = "DejaVu Sans Mono"

[font.italic]
family = "DejaVu Sans Mono"

[font.normal]
family = "DejaVu Sans Mono"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true

[window.padding]
x = 0
y = 0

[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
post_processing = true
action = 'Copy'

  [hints.enabled.mouse]
  enabled = true
  mods = 'Control'
