#!/bin/sh
# $Xorg: xinitrc.cpp,v 1.3 2000/08/17 19:54:30 cpqbld Exp $

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

setterm -blank 0 -powersave off -powerdown 0
xset s off

rm -rf /tmp/ssh-??????????
killall ssh-agent
eval `ssh-agent -s`


# merge in defaults and keymaps
[ -f $sysresources ] && /usr/bin/xrdb -merge $sysresources
[ -f $sysmodmap ] && /usr/bin/xmodmap $sysmodmap
[ -f $userresources ] && /usr/bin/xrdb -merge $userresources
[ -f $usermodmap ] && /usr/bin/xmodmap $usermodmap

xmodmap -e 'keycode 66 = Escape'
xmodmap -e 'clear Lock'

# Create default user directory & populate it if not already existent
#if [ ! -d $HOME/.config/openbox ]; then
#  mkdir -p $HOME/.config/openbox
#  cat /etc/xdg/openbox/menu.xml > $HOME/.config/openbox/menu.xml
#  cat /etc/xdg/openbox/rc.xml > $HOME/.config/openbox/rc.xml
#fi

if [ -r /etc/xprofile ]; then
    source /etc/xprofile
fi
if [ -r $HOME/.xprofile ]; then
    source $HOME/.xprofile
fi

if [ -z "$DESKTOP_SESSION" -a -x /usr/bin/ck-launch-session ]; then
  exec ck-launch-session dbus-launch --exit-with-session /usr/bin/i3
else
  exec /usr/bin/i3
fi

#exec openbox-session
#exec openbox
