#!/bin/sh

if [ -n "$DESKTOP_SESSION" ] ; then
    eval $(gnome-keyring-daemon --replace --components=ssh,secrets,pkcs11,gpg)
    export SSH_AUTH_SOCK
    export GNOME_KEYRING_CONTROL
fi

[[ -f /home/davs/.xsession ]] && source /home/davs/.xsession
[[ -f /home/davs/.xsessionrc ]] && source /home/davs/.xsessionrc
